// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMonitors():Promise<Array<string>>;

export function SelectMonitor(arg1:number):Promise<boolean>;

export function SetCombinedMode():Promise<void>;

export function StartCapture():Promise<void>;

export function StopCapture():Promise<void>;
