// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMonitors() {
  return window['go']['main']['App']['ListMonitors']();
}

export function SelectMonitor(arg1) {
  return window['go']['main']['App']['SelectMonitor'](arg1);
}

export function SetCombinedMode() {
  return window['go']['main']['App']['SetCombinedMode']();
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
